### ISSUE TITLE
Easier access to specific applications

### ISSUE THREAD

**Issue by citharus** [repose-theme/repose#10]
You should consider converting the repo to an organization there for the applications can get there own repo for easier cloning.

**Comment by l4ssc** [comment]
Makes sense. I'll do this soon.

**Comment by l4ssc** [comment]
I've created various private repositories for the purpose of doing this, they will be publicized as I move them over.

**For future contributors:** Do not PR to implement color schemes (the only remnant of this is #9, which will stay for ease of access) after this point! Simply create a repository for your port and create an issue to let me know that you would like to transfer your repo to the organization.

**Comment by 18gatenmaker** [comment]
Do I get to keep my fork, or should I create a seperate repo?

**Comment by l4ssc** [comment]
keep the fork, I'll merge in and then split it into its own repo
